In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r"D:\Open Source\Data-Science-Revision\Panda\movies_data.csv", encoding_errors = "replace")

In [21]:
df

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
0,13 Hours,Michael Bay,144,Toby Stephens,James Badge Dale,David Costabile,Action,50000000,69400000,50.00,69.23,19400000,0,0.0,2016,7.4
1,16 Blocks,Richard Donner,102,Bruce Willis,David Zayas,Sasha Roiz,Action,52000000,65000000,33.33,50.00,13000000,0,0.0,2006,6.6
2,17 Again,Burr Steers,102,Matthew Perry,Hunter Parrish,Thomas Lennon,Comedy,20000000,139000000,44.44,25.00,119000000,0,0.0,2009,6.4
3,1982,Tommy Oliver,90,Bokeem Woodbine,Ruby Dee,Quinton Aaron,Drama,1000000,2000000,50.00,100.00,1000000,0,0.0,2013,7.1
4,2 Fast 2 Furious,John Singleton,107,Paul Walker,Cole Hauser,Mo Gallini,Action,76000000,236000000,75.00,42.85,160000000,0,0.0,2003,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3969,Z Storm,David Lam,92,Michael Wong,Louis Koo,Stephen Au,Action,7000000,17000000,100.00,100.00,10000000,0,0.0,2014,5.3
3970,Zack and Miri Make a Porno,Kevin Smith,101,Gerry Bednob,Jeff Anderson,Jennifer Schwalbach Smith,Comedy,24000000,42000000,66.67,41.66,18000000,0,0.0,2008,6.6
3971,Zero Effect,Jake Kasdan,116,Kim Dickens,Ryan O'Neal,Angela Featherstone,Comedy,5000000,2000000,33.33,50.00,-3000000,0,0.0,1998,7.0
3972,Zombieland,Ruben Fleischer,88,Emma Stone,Bill Murray,Derek Graf,Adventure,23600000,102000000,66.67,33.33,78400000,0,0.0,2009,7.7
3973,Zulu,J�r?me Salle,110,Orlando Bloom,Tanya van Graan,Conrad Kemp,Crime,16000000,5000000,0.00,0.00,-11000000,0,0.0,2013,6.7

In [23]:
df[['Director','Box Office','IMDb score']]

             Director  Box Office  IMDb score
0         Michael Bay    69400000         7.4
1      Richard Donner    65000000         6.6
2         Burr Steers   139000000         6.4
3        Tommy Oliver     2000000         7.1
4      John Singleton   236000000         5.9
...               ...         ...         ...
3969        David Lam    17000000         5.3
3970      Kevin Smith    42000000         6.6
3971      Jake Kasdan     2000000         7.0
3972  Ruben Fleischer   102000000         7.7
3973     J�r?me Salle     5000000         6.7

[3974 rows x 3 columns]

In [31]:
# finds by row label
df.loc[1]

Movie                                       16 Blocks
Director                               Richard Donner
Running time                                      102
Actor 1                                  Bruce Willis
Actor 2                                   David Zayas
Actor 3                                    Sasha Roiz
Genre                                          Action
Budget                                       52000000
Box Office                                   65000000
Actors Box Office %                             33.33
Director Box Office %                            50.0
Earnings                                     13000000
Oscar and Golden Globes nominations                 0
Oscar and Golden Globes awards                    0.0
Release year                                     2006
IMDb score                                        6.6
Name: 1, dtype: object

In [29]:
# finds by row index
df.iloc[1]

Movie                                       16 Blocks
Director                               Richard Donner
Running time                                      102
Actor 1                                  Bruce Willis
Actor 2                                   David Zayas
Actor 3                                    Sasha Roiz
Genre                                          Action
Budget                                       52000000
Box Office                                   65000000
Actors Box Office %                             33.33
Director Box Office %                            50.0
Earnings                                     13000000
Oscar and Golden Globes nominations                 0
Oscar and Golden Globes awards                    0.0
Release year                                     2006
IMDb score                                        6.6
Name: 1, dtype: object

In [33]:
df.loc[4,'Box Office']

np.int64(236000000)

In [35]:
df.iloc[4,8]

np.int64(236000000)

In [37]:
df.loc[5:15, ['Movie','Director','Genre']]

                      Movie             Director   Genre
5                    2 Guns    Baltasar Korm�kur  Action
6                      2012      Roland Emmerich  Action
7                        21       Robert Luketic   Crime
8            22 Jump Street            Phil Lord  Action
9                27 Dresses        Anne Fletcher  Comedy
10              3 Backyards      Eric Mendelsohn   Drama
11         30 Days of Night          David Slade  Horror
12                      300          Zack Snyder  Action
13   300: Rise of an Empire           Noam Murro  Action
14  3000 Miles to Graceland  Demian Lichtenstein  Action
15                 47 Ronin          Carl Rinsch  Action

In [39]:
df.iloc[5:16,[0,1,6]]

                      Movie             Director   Genre
5                    2 Guns    Baltasar Korm�kur  Action
6                      2012      Roland Emmerich  Action
7                        21       Robert Luketic   Crime
8            22 Jump Street            Phil Lord  Action
9                27 Dresses        Anne Fletcher  Comedy
10              3 Backyards      Eric Mendelsohn   Drama
11         30 Days of Night          David Slade  Horror
12                      300          Zack Snyder  Action
13   300: Rise of an Empire           Noam Murro  Action
14  3000 Miles to Graceland  Demian Lichtenstein  Action
15                 47 Ronin          Carl Rinsch  Action

In [45]:
df.at[6,'Movie']

'2012'

In [47]:
df.iat[6,0]

'2012'

In [55]:
df[df['IMDb score']>9]

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
1901,The Shawshank Redemption,Frank Darabont,142,Morgan Freeman,Jeffrey DeMunn,Bob Gunton,Crime,25000000,28000000,50.00,50.00,3000000,7,0.0,1994,9.3
1940,The Godfather,Francis Ford Coppola,175,Al Pacino,Marlon Brando,Robert Duvall,Crime,6000000,250000000,59.36,72.72,244000000,10,7.0,1972,9.2
2792,Kickboxer: Vengeance,John Stockwell,90,Matthew Ziff,T.J. Storm,Sam Medina,Action,17000000,3000000,0.00,0.00,-14000000,0,0.0,2016,9.1

In [77]:
df[(df['IMDb score']>8) & (df['Earnings']>500_000_000)]

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
995,The Dark Knight Rises,Christopher Nolan,164,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action,250000000,1081000000,100.00,100.00,831000000,0,0.0,2012,8.5
1402,Deadpool,Tim Miller,108,Ryan Reynolds,Ed Skrein,Stefan Kapicic,Action,58000000,786000000,100.00,100.00,728000000,1,0.0,2016,8.1
1684,Guardians of the Galaxy,James Gunn,121,Bradley Cooper,Vin Diesel,Djimon Hounsou,Action,170000000,773000000,63.88,33.33,603000000,2,0.0,2014,8.1
1690,Inside Out,Pete Docter,95,Amy Poehler,Mindy Kaling,Phyllis Smith,Animation,175000000,858000000,83.33,100.00,683000000,2,1.0,2015,8.3
1721,The Avengers,Joss Whedon,173,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,Action,220000000,1519000000,90.47,75.00,1299000000,2,0.0,2012,8.1
1762,Jurassic Park,Steven Spielberg,127,Wayne Knight,Ariana Richards,Bob Peck,Sci-Fi,63000000,1040000000,100.00,84.60,977000000,3,3.0,1993,8.1
1818,The Lion King,Roger Allers,73,Matthew Broderick,Nathan Lane,Niketa Calame,Animation,45000000,986000000,33.33,100.00,941000000,4,2.0,1994,8.5
1833,Captain America: Civil War,Anthony Russo,147,Robert Downey Jr.,Scarlett Johansson,Chris Evans,Action,250000000,1153000000,100.00,50.00,903000000,5,2.0,2016,8.2
1840,Finding Nemo,Andrew Stanton,100,Alexander Gould,Stephen Root,Brad Garrett,Animation,94000000,940000000,30.95,66.67,846000000,5,1.0,2003,8.2
1866,Interstellar,Christopher Nolan,169,Matthew McConaughey,Anne Hathaway,Mackenzie Foy,Adventure,165000000,702000000,51.58,100.00,537000000,6,1.0,2014,8.6
1870,Pirates of the Caribbean: The Curse of the Bla...,Gore Verbinski,143,Johnny Depp,Orlando Bloom,Jack Davenport,Action,140000000,654000000,52.25,57.14,514000000,6,1.0,2003,8.1
1878,The Sixth Sense,M. Night Shyamalan,107,Bruce Willis,Haley Joel Osment,Olivia Williams,Drama,40000000,673000000,52.77,77.00,633000000,6,1.0,1999,8.1
1881,Up,Pete Docter,96,John Ratzenberger,Delroy Lindo,Jess Harnell,Animation,175000000,731000000,66.67,100.00,556000000,6,2.0,2009,8.3
1898,The Martian,Ridley Scott,151,Matt Damon,Donald Glover,Benedict Wong,Adventure,108000000,630000000,83.33,35.29,522000000,7,2.0,2015,8.1
1916,The Dark Knight,Christopher Nolan,152,Christian Bale,Heath Ledger,Morgan Freeman,Action,185000000,1000000000,86.66,100.00,815000000,8,2.0,2008,9.0
1952,Inception,Christopher Nolan,148,Leonardo DiCaprio,Tom Hardy,Joseph Gordon-Levitt,Action,160000000,837000000,66.67,100.00,677000000,12,4.0,2010,8.8
1959,Forrest Gump,Robert Zemeckis,142,Tom Hanks,Siobhan Fallon Hogan,Sam Anderson,Comedy,55000000,683000000,58.33,61.50,628000000,13,6.0,1994,8.8
1961,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,171,Christopher Lee,Orlando Bloom,Billy Boyd,Action,93000000,887000000,66.67,72.72,794000000,13,4.0,2001,8.8
1966,The Lord of the Rings: The Two Towers,Peter Jackson,172,Christopher Lee,Orlando Bloom,Billy Boyd,Action,94000000,947000000,66.67,72.72,853000000,16,6.0,2002,8.7
1968,The Lord of the Rings: The Return of the King,Peter Jackson,192,Orlando Bloom,Billy Boyd,Bernard Hill,Action,94000000,1142000000,55.55,72.72,1048000000,18,11.0,2003,8.9
3157,Raiders of the Lost Ark,Steven Spielberg,115,Harrison Ford,Karen Allen,William Hootkins,Action,18000000,768000000,100.00,84.60,750000000,13,12.0,1981,8.5
3358,Star Wars: Episode IV - A New Hope,George Lucas,125,Harrison Ford,Peter Cushing,Kenny Baker,Action,11000000,775000000,100.00,100.00,764000000,11,7.0,1977,8.7
3359,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,127,Harrison Ford,Kenny Baker,Anthony Daniels,Action,18000000,550000000,100.00,50.00,532000000,4,2.0,1980,8.8